apiVersion: v1
kind: Pod
metadata:
  name: wordpress
spec:
  containers:
  - image: wordpress
    name: wordpress
    env:
    - name: BDPASS
      valueFrom:
        secretKeyRef:
          name: dotfile-secret
          key: BDPASS
    - name: DBUSER
      valueFrom:
        secretKeyRef:
          name: dotfile-secret
          key: DBUSER