apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment1.name }}
  labels:
    app: nginx
spec:
  replicas: {{ .Values.deployment1.replicas }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: {{ .Values.deployment1.repository.image }}:{{ .Values.deployment1.repository.tag }}
        ports:
        - containerPort: {{ .Values.deployment1.port }}