apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service2.name }}
spec:
  selector:
    app: nginx2
  ports:
    - protocol: TCP
      port: {{ .Values.service2.port }}
      targetPort: {{ .Values.deployment2.port }}
  type: {{ .Values.service2.type }}